name: Build image
on: [push]

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        variant: [rpi, base]

    steps:
    - uses: actions/checkout@v4

    - name: Modify Containerfile for base variant
      if: matrix.variant == 'base'
      run: sed -i 's/almalinux-bootc-rpi:/almalinux-bootc:/' Containerfile

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE }}
        tags: ${{ github.run_number }}-${{ matrix.variant }}
        containerfiles: |
          ./Containerfile
        build-args: |
          NASPI_REPO=${{ github.server_url }}/${{ github.repository }}.git

    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      if: github.ref == 'refs/heads/main'
      with:
        registry: ${{ env.REGISTRY }}
        image: ${{ env.IMAGE }}
        tags: ${{ github.run_number }}-${{ matrix.variant }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
